version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: docker/docker/python/Dockerfile
    container_name: 'app-docker-2'
    volumes:
      - .:/application
    ports:
      - '8080:8080'
    environment:
      PYTHONBUFFERED: 1
    networks:
      - app
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0.29
    volumes:
      - ./docker/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: artur
      MYSQL_PASSWORD: flask
    ports:
      - "5632:3306"
    networks:
      - app

networks:
  app:
    driver: bridge


#sudo docker-compose exec mysql bash
#mysql -u root -p^C